name: tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:

      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.6, 3.7]

    env:
      OE_LICENSE: $HOME/oe_license.txt

    steps:
      - uses: actions/checkout@v1
      - name: Additional info about the build
        run: |
        shell: bash
          uname -a
          df -h
          ulimit -a

      - name: Configure conda
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate
          conda config --set always_yes True
          conda config --add channels omnia --add channels conda-forge --add channels openeye
          conda update --quiet --all
          conda install conda conda-build jinja2 anaconda-client
          conda info
          conda list
        env:
          OPERATING_SYSTEM: ${{ matrix.os }}

      - name: Decrypt OpenEye license
        shell: bash
        run: |
          echo "${ENC_OE_LICENSE}" > $HOME/oe_license.txt
        env:
          ENC_OE_LICENSE: ${{ secrets.ENC_OE_LICENSE }}

      - name: Create test environment
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate
          python devtools/scripts/create_conda_env.py -n=test -p=${{ matrix.python-version }} devtools/conda-envs/test_env.yaml

      - name: Install package
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate test
          python setup.py develop --no-deps

      - name: Run tests
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate test
          pytest -v --cov=bayesiantesting bayesiantesting/tests/

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black

      - name: Run black
        run: |
          black bayesiantesting --check
          black studies --check

      - name: Run flake8
        run: |
          flake8 bayesiantesting
          flake8 studies